version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  
  fastapi:
    build:
      context: ..
      dockerfile: services/backend/Dockerfile
    volumes:
      - ../storage:/app/storage
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - WEBSITE_URL=http://site
      - INPUT_QUEUE=output
      - OUTPUT_QUEUE=input
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - rabbitmq
  
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:23.11-py3
    command: ["tritonserver", "--model-repository=/models"]
    volumes:
      - ../models/tensorrt_models_running:/models      # Папка с движками моделей и конфигами
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:                                     # Разрешение на использование GPU
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ['0']
              driver: nvidia
  
  adapter:
    build:
      context: ..
      dockerfile: services/adapter/Dockerfile   
    volumes:
      - ../storage:/app/storage      # Монтируемое хранилилище
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - INPUT_QUEUE=input
      - OUTPUT_QUEUE=output
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq
  
  php-apache-environment:
    container_name: php-apache
    hostname: site
    build:
      context: ..
      dockerfile: services/frontend/public_html/docker/php-apache/Dockerfile
    volumes:
      - ../services/frontend/public_html/src:/var/www/html/
      - ../services/frontend/public_html/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - BACKEND_API_URL=http://fastapi
      - SITE_PORT=${FRONTEND_PORT}
    env_file:
      - ./.env
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT