FROM python:3.10

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY ./adapter/requirements.txt ./
RUN pip install -r requirements.txt

WORKDIR adapter_triton

COPY ../adapter adapter/
COPY ../rabbit rabbit/

CMD ["python", "-m", "adapter"]
